DROP TABLE IF EXISTS favourites CASCADE;
CREATE TABLE favourites (
  id SERIAL PRIMARY KEY NOT NULL,
  mentee_id INTEGER REFERENCES users(id) on DELETE CASCADE,
  mentor_id INTEGER REFERENCES users(id) on DELETE CASCADE
);