DROP TABLE IF EXISTS mentor_reviews CASCADE;
-- CREATE URLS
CREATE TABLE mentor_reviews (
  id SERIAL PRIMARY KEY,
  mentor_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  mentee_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  rating SMALLINT NOT NULL DEFAULT 0,
  message VARCHAR(255)
);

